override:
  nginx:
    servers:
      default: [
        "listen 80;",
        "listen [::]:80 default_server;",
        "",
        "root /srv/http;",
        "index index.php index.htm index.html;",
        "",
        "location ~ .php$ {",
        "        root /srv/http;",
        "        fastcgi_pass 127.0.0.1:9999;",
        "        fastcgi_index  index.php;",
        "        fastcgi_param  SCRIPT_FILENAME /srv/http$fastcgi_script_name;",
        "        include fastcgi_params;",
        "}",
        "",
        "location ~ /\\.ht {",
        "        deny  all;",
        "}",
        "",
        "location = /robots.txt {",
        "        allow all;",
        "        log_not_found off;",
        "        access_log off;",
        "}",
        "",
        "location / {",
        "        try_files $uri $uri/ /index.php?$args;",
        "}",
        "",
        "location /favicon.ico {",
        "        access_log  off;",
        "        log_not_found  off;",
        "        expires  1d;",
        "}",
        "",
        "location ~* \\.(js|css|png|jpg|jpeg|gif|ico)$ {",
        "        expires max;",
        "        log_not_found off;",
        "}",
      ]